export const GET_LOCATION = "GET_LOCATION";

export const GET_MAJSTORS = "GET_MAJSTORS";
export const GET_LOCAL_MAJSTORS = "GET_LOCAL_MAJSTORS";
export const FETCH_START = "GET_MAJSTORS";

export const SET_CATEGORY = "SET_CATEGORY";
export const SET_LOCAL = "SET_LOCAL";
export const SET_MAJSTOR = "SET_MAJSTOR";


export const INTRO_COMPLETED_CHECK = "INTRO_COMPLETED_CHECK";


